# Docker image that compiles the traditional Spring Boot jar
FROM maven:3.6.3-openjdk-11 AS BUILD
ADD . /build
WORKDIR /build
RUN mvn -ntp package

# Docker image that packages the traditional Spring Boot application
FROM openjdk:11-jre-slim
COPY --from=BUILD "/build/target/books-0.0.1-SNAPSHOT.jar" app.jar
ENTRYPOINT ["java","-jar","/app.jar", "--server.port=8081"]